{{ if .Values.features.backups.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: backups
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-k8up
    helm:
      releaseName: k8up
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backups
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/externalName
{{ end }}