{{ if .Values.features.mariadb.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-mariadb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-mariadb-operator
    helm:
      releaseName: mariadb-operator
      valuesObject:
      {{- toYaml .Values.features.mariadb | nindent 8 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mariadb-operator
{{ end }}