apiVersion: v1
kind: Service
metadata:
  name: prometheus-smartctl-exporter
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: prometheus-smartctl-exporter
    app.kubernetes.io/name: prometheus-smartctl-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9633
      targetPort: 9633
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: prometheus-smartctl-exporter
