global:
  values:
    cluster: changeme
  argocd_namespace: argocd
features:
  backups:
    enabled: true
    namespace: backups
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-backups
  cert-manager-configs:
    enabled: true
    namespace: cert-manager
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-cert-manager-configs
  cloudflared:
    enabled: true
    namespace: cloudflared
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-cloudflared
  externaldns:
    enabled: false
    namespace: externaldns
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-externaldns
  ingress-nginx:
    enabled: true
    namespace: ingress-nginx
    source:
      repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.3
    values:
      controller:
        ingressClassResource:
          default: true
  kube-state-metrics:
    enabled: true
    namespace: monitoring
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-kube-state-metrics
  longhorn:
    enabled: false
    namespace: longhorn-system
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-longhorn
  mariadb-operator:
    enabled: false
    namespace: mariadb-operator
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-mariadb-operator
  metallb-configs:
    enabled: false
    namespace: metallb
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-metallb-configs
  metallb:
    enabled: false
    namespace: metallb
    source:
      repoURL:  https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.2
  node-exporter:
    enabled: true
    namespace: monitoring
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-node-exporter
  openebs:
    enabled: true
    namespace: openenbs
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-openebs
    values:
      storageclasses:
        zfs:
          enabled: false
          poolname: "zfspv-pool"
  reloader:
    enabled: true
    namespace: reloader
    source:
      repoURL: https://stakater.github.io/stakater-charts
      chart: reloader
      targetRevision: 2.1.3
  smartctl-exporter:
    enabled: false
    namespace: monitoring
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-smartctl-exporter
  vmagent:
    enabled: true
    namespace: monitoring
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-vmagent
  vmoperator:
    enabled: true
    namespace: monitoring
    source:
      repoURL: https://github.com/danfoster/zem-gitops
      targetRevision: main
      path: apps/infra/zem-vmoperator