features:
  openebs:
    enabled: false
    storageclasses:
      zfs:
        enabled: false
        poolname: "zfspv-pool"
  ingressnginx:
    enabled: true
    controller:
      ingressClassResource:
        default: true
  metallb:
    enabled: false
  reloader:
    enabled: true
  externaldns:
    enabled: false
  certmanager:
    enabled: true
  kube_state_metrics:
    enabled: true
  node_exporter:
    enabled: true
  vmagent:
    enabled: true
    victoria-metrics-agent:
    config:
      global:
        external_labels:
          cluster: "{{. Value.cluster.name}}"
  vmoperator:
    enabled: true
  zfs_exporter:
    enabled: false
  smartctl_exporter:
    enabled: false
  backups:
    enabled: true
  longhorn:
    enabled: false