apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backups-pce-{{.Values.env }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pce-{{ .Values.env }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: apps/infra/zem-backups
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pce-{{ .Values.env }}
