apiVersion: k8s.mariadb.com/v1alpha1
kind: ExternalMariaDB
metadata:
  name: oci-mysql
spec:
  host: "{{ .Values.mysql.host }}"
  port: 3306
  username: admin
  passwordSecretKeyRef:
    name: mysql-root-creds
    key: password
