apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-frontend
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: "{{.Values.ingress.hostname}}"
      port:
        number: 80
  tls:
    - hosts:
        - longhorn-frontend
