# This file contains valid test values for the Helm chart's JSON schema.
# Use 'helm lint --values values_linter.yaml .' to test.

cloudflare-tunnel:
  replicas: 1
  cloudflare:
    secretName: cloudflared-secret
    tunnelName: zem-tunnel
    account: "my-cloudflare-account-tag"
    tunnelId: "a-valid-tunnel-id"