# Snapshot controller configuration
controller:
  replicas: 2
  image:
    repository: registry.k8s.io/sig-storage/snapshot-controller
    tag: v8.2.0
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# VolumeSnapshotClass for OCI Block Volumes
volumeSnapshotClass:
  oci:
    enabled: true
    name: oci-bv-snapclass
    driver: blockvolume.csi.oraclecloud.com
    deletionPolicy: Delete
    isDefault: true
