backup:
  schedule: "@daily-random"
check:
  schedule: "@weekly-random"
prune:
  schedule: "@weekly-random"
  retention:
    keepLast: 5
    keepDaily: 14
    keepWeekly: 8
    keepMonthly: 12
    keepYearly: 5